import type { ScientistProfile, IntentAsset, ActivityLog } from '@/types';

export const MOCK_SCIENTISTS: ScientistProfile[] = [
  {
    id: 'sci_001',
    fullName: 'Dr. Evelyn Reed',
    email: 'evelyn.reed@stanford.edu',
    handle: '@evelyn_reed',
    affiliation: 'Stanford University',
    bio: 'Specializing in cellular senescence and cardiac tissue regeneration. PI at the Reed Lab focusing on translational approaches to reverse age-related fibrosis using novel mRNA delivery systems.',
    status: 'approved',
    tags: ['#Longevity', '#AI-Bio', '#Tier-1'],
  },
  {
    id: 'sci_002',
    fullName: 'Dr. Marcus Chen',
    email: 'marcus.chen@mit.edu',
    handle: '@m_chen_neuro',
    affiliation: 'MIT',
    bio: 'Computational neuroscientist working on brain-computer interfaces and neural decoding algorithms. Leading research in non-invasive neural signal processing for cognitive enhancement.',
    status: 'approved',
    tags: ['#Neuroscience', '#AI-Bio', '#Tier-1'],
  },
  {
    id: 'sci_003',
    fullName: 'Dr. Aria Patel',
    email: 'aria.patel@caltech.edu',
    handle: '@ariapatel_gen',
    affiliation: 'Caltech',
    bio: 'Genomics researcher focused on CRISPR-based gene therapies for rare genetic disorders. Pioneer in high-throughput screening methods for guide RNA optimization.',
    status: 'approved',
    tags: ['#Genomics', '#DeSci', '#Tier-2'],
  },
];

export const MOCK_INTENTS: IntentAsset[] = [
  {
    id: 'intent_001',
    scientistId: 'sci_001',
    title: 'Targeting Senescent Cells to Reverse Cardiac Fibrosis',
    ticker: '$CELL-01',
    coreHypothesis: 'Targeting senescent cells to reverse cardiac fibrosis by innovating senescent cell elimination pathways. Our approach involves developing a novel mRNA-based therapeutic that selectively identifies and clears senescent cardiomyocytes, reducing fibrotic tissue accumulation and restoring cardiac function in aged hearts.',
    evidenceLinks: ['https://github.com/reedlab/cardiac-senescence', 'https://arxiv.org/abs/2401.12345'],
    fundingGoalUSDC: 150000,
    escrowedAmountUSDC: 120000,
    status: 'published',
    aiScore: 94,
    tags: ['#Longevity', '#AI-Bio', '#Tier-1'],
    supporterCount: 2500,
    trendingRank: 1,
    resourceAsks: [
      { type: 'compute', description: 'H100 GPU Hours for molecular simulation', quantity: '500 H100 Hrs' },
    ],
    backers: [
      { id: 'backer_001', name: 'Advaita Labs' },
    ],
    patrons: [
      { id: 'patron_001', name: 'Alice W.', amountUSDC: 50000 },
      { id: 'patron_002', name: 'Bob K.', amountUSDC: 30000 },
      { id: 'patron_003', name: 'Carol M.', amountUSDC: 25000 },
      { id: 'patron_004', name: 'David L.', amountUSDC: 15000 },
    ],
    milestones: [
      {
        id: 'ms_001_1',
        intentId: 'intent_001',
        order: 1,
        label: 'M1',
        sublabel: 'Dataset',
        estTime: '3 months',
        objective: 'Compile comprehensive senescent cell biomarker dataset from cardiac tissue samples',
        deliverables: 'Published dataset on GitHub with 10,000+ annotated samples',
        verificationCriteria: 'Dataset passes quality audit with >95% annotation accuracy',
        releaseAmountUSDC: 40000,
        status: 'in_progress',
      },
      {
        id: 'ms_001_2',
        intentId: 'intent_001',
        order: 2,
        label: 'M2',
        sublabel: 'in-Vitro',
        estTime: '6 months',
        objective: 'Demonstrate selective senescent cell clearance in vitro cardiac tissue models',
        deliverables: 'Published results showing >70% senescent cell reduction',
        verificationCriteria: 'Peer-reviewed preprint with reproducible protocol',
        releaseAmountUSDC: 55000,
        status: 'locked',
      },
      {
        id: 'ms_001_3',
        intentId: 'intent_001',
        order: 3,
        label: 'M3',
        sublabel: 'in-Vivo',
        estTime: '12 months',
        objective: 'Validate therapeutic efficacy in murine cardiac fibrosis model',
        deliverables: 'Animal study data showing significant fibrosis reduction',
        verificationCriteria: 'Statistical significance p<0.05 in primary endpoints',
        releaseAmountUSDC: 55000,
        status: 'locked',
      },
    ],
  },
  {
    id: 'intent_002',
    scientistId: 'sci_002',
    title: 'Non-Invasive Neural Decoding for Cognitive Enhancement',
    ticker: '$NEUR-01',
    coreHypothesis: 'Developing a novel non-invasive neural decoding algorithm that leverages transformer architectures to interpret EEG signals with unprecedented accuracy, enabling real-time cognitive state monitoring and targeted neurofeedback for enhanced learning and memory consolidation.',
    evidenceLinks: ['https://github.com/chenlab/neural-decode'],
    fundingGoalUSDC: 200000,
    escrowedAmountUSDC: 45000,
    status: 'published',
    aiScore: 87,
    tags: ['#Neuroscience', '#AI-Bio', '#Tier-1'],
    supporterCount: 890,
    trendingRank: 3,
    resourceAsks: [
      { type: 'compute', description: 'A100 GPU for model training', quantity: '1000 A100 Hrs' },
      { type: 'data', description: 'EEG dataset access', quantity: '50TB Neural Data' },
    ],
    backers: [
      { id: 'backer_002', name: 'NeuroTech Collective' },
    ],
    patrons: [
      { id: 'patron_005', name: 'Elena S.', amountUSDC: 25000 },
      { id: 'patron_006', name: 'Frank J.', amountUSDC: 20000 },
    ],
    milestones: [
      {
        id: 'ms_002_1',
        intentId: 'intent_002',
        order: 1,
        label: 'M1',
        sublabel: 'Dataset',
        estTime: '4 months',
        objective: 'Curate and preprocess multi-subject EEG dataset for decoder training',
        deliverables: 'Cleaned dataset with 500+ hours of annotated EEG recordings',
        verificationCriteria: 'Dataset published with documented preprocessing pipeline',
        releaseAmountUSDC: 60000,
        status: 'in_progress',
      },
      {
        id: 'ms_002_2',
        intentId: 'intent_002',
        order: 2,
        label: 'M2',
        sublabel: 'Model',
        estTime: '8 months',
        objective: 'Train and validate transformer-based neural decoder achieving >85% accuracy',
        deliverables: 'Open-source model with benchmark results',
        verificationCriteria: 'Accuracy verified on held-out test set by independent reviewer',
        releaseAmountUSDC: 80000,
        status: 'locked',
      },
      {
        id: 'ms_002_3',
        intentId: 'intent_002',
        order: 3,
        label: 'M3',
        sublabel: 'Trial',
        estTime: '14 months',
        objective: 'Conduct pilot human study demonstrating cognitive enhancement',
        deliverables: 'IRB-approved study results with 30+ participants',
        verificationCriteria: 'Statistically significant improvement in cognitive metrics',
        releaseAmountUSDC: 60000,
        status: 'locked',
      },
    ],
  },
  {
    id: 'intent_003',
    scientistId: 'sci_003',
    title: 'CRISPR Guide RNA Optimization via High-Throughput Screening',
    ticker: '$GENE-01',
    coreHypothesis: 'Applying machine learning-driven high-throughput screening to identify optimal CRISPR guide RNAs for rare genetic disorders, reducing off-target effects by 90% compared to current computational prediction methods.',
    evidenceLinks: ['https://github.com/patellab/crispr-screen'],
    fundingGoalUSDC: 100000,
    escrowedAmountUSDC: 10000,
    status: 'published',
    aiScore: 79,
    tags: ['#Genomics', '#DeSci', '#Tier-2'],
    supporterCount: 340,
    resourceAsks: [
      { type: 'equipment', description: 'Lab equipment rental', quantity: '6 months access' },
    ],
    backers: [],
    patrons: [
      { id: 'patron_007', name: 'Grace H.', amountUSDC: 10000 },
    ],
    milestones: [
      {
        id: 'ms_003_1',
        intentId: 'intent_003',
        order: 1,
        label: 'M1',
        sublabel: 'Screen',
        estTime: '3 months',
        objective: 'Complete high-throughput screening of 100,000+ guide RNA candidates',
        deliverables: 'Screening results and ranked guide RNA database',
        verificationCriteria: 'Database published with full experimental protocols',
        releaseAmountUSDC: 35000,
        status: 'in_progress',
      },
      {
        id: 'ms_003_2',
        intentId: 'intent_003',
        order: 2,
        label: 'M2',
        sublabel: 'Validate',
        estTime: '7 months',
        objective: 'Validate top 50 guide RNAs in cell line models',
        deliverables: 'Validation data showing off-target reduction metrics',
        verificationCriteria: 'Independent lab replication of top 10 candidates',
        releaseAmountUSDC: 35000,
        status: 'locked',
      },
      {
        id: 'ms_003_3',
        intentId: 'intent_003',
        order: 3,
        label: 'M3',
        sublabel: 'Publish',
        estTime: '10 months',
        objective: 'Publish ML model and optimized guide RNA library',
        deliverables: 'Open-source ML model + curated guide RNA database',
        verificationCriteria: 'Peer-reviewed publication and community adoption metrics',
        releaseAmountUSDC: 30000,
        status: 'locked',
      },
    ],
  },
];

const now = Date.now();

export const MOCK_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log_init_1',
    timestamp: now - 120_000,
    type: 'patronage',
    message: '💰 David L. funded 15,000 USDC to $CELL-01',
    ticker: '$CELL-01',
    intentId: 'intent_001',
  },
  {
    id: 'log_init_2',
    timestamp: now - 300_000,
    type: 'ai_verified',
    message: '🛡️ AI Gatekeeper verified $NEUR-01 M0. Fundraising milestone cleared.',
    ticker: '$NEUR-01',
    intentId: 'intent_002',
  },
  {
    id: 'log_init_3',
    timestamp: now - 600_000,
    type: 'proof_submitted',
    message: '📄 Dr. Evelyn Reed submitted proof for $CELL-01 M1',
    ticker: '$CELL-01',
    intentId: 'intent_001',
  },
  {
    id: 'log_init_4',
    timestamp: now - 900_000,
    type: 'patronage',
    message: '💰 Carol M. funded 25,000 USDC to $CELL-01',
    ticker: '$CELL-01',
    intentId: 'intent_001',
  },
  {
    id: 'log_init_5',
    timestamp: now - 1_200_000,
    type: 'intent_published',
    message: '🧬 New intent $GENE-01 published: "CRISPR Guide RNA Optimization"',
    ticker: '$GENE-01',
    intentId: 'intent_003',
  },
  {
    id: 'log_init_6',
    timestamp: now - 1_500_000,
    type: 'patronage',
    message: '💰 Elena S. funded 25,000 USDC to $NEUR-01',
    ticker: '$NEUR-01',
    intentId: 'intent_002',
  },
  {
    id: 'log_init_7',
    timestamp: now - 1_800_000,
    type: 'intent_published',
    message: '🧬 New intent $NEUR-01 published: "Non-Invasive Neural Decoding"',
    ticker: '$NEUR-01',
    intentId: 'intent_002',
  },
  {
    id: 'log_init_8',
    timestamp: now - 2_400_000,
    type: 'patronage',
    message: '💰 Alice W. funded 50,000 USDC to $CELL-01',
    ticker: '$CELL-01',
    intentId: 'intent_001',
  },
  {
    id: 'log_init_9',
    timestamp: now - 3_000_000,
    type: 'intent_published',
    message: '🧬 New intent $CELL-01 published: "Targeting Senescent Cells to Reverse Cardiac Fibrosis"',
    ticker: '$CELL-01',
    intentId: 'intent_001',
  },
];
